version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "flexget"
    automerged_updates:
      - match:
          update_type: "semver:patch"

